apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: sp0re90/jenkins-docker
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home-persistent
              mountPath: /var/jenkins_home
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
        - name: jenkins-home-persistent
          persistentVolumeClaim:
            claimName: jenkins-home-pv-claim
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock

---
apiVersion: v1
kind: PersistentVolumeClaim        # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                          # Claim name and labels
  name: jenkins-home-pv-claim
  namespace: jenkins
  labels:
    app: jenkins
spec:                              # Access mode and resource limits
  storageClassName: standard       # Request a certain storage class
  accessModes:
    - ReadWriteOnce                # ReadWriteOnce means the volume can be mounted as read-write by a single Node
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume            # Create a PersistentVolume
metadata:
  name: jenkins-home-pv
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: standard      # Storage class. A PV Claim requesting the same storageClass can be bound to this volume.
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:                       # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/mnt/jenkins/data"
  persistentVolumeReclaimPolicy: Retain  # Retain the PersistentVolume even after PersistentVolumeClaim is deleted. The volume is considered “released”. But it is not yet available for another claim because the previous claimant’s data remains on the volume.

