apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: sp0re90/jenkins-docker
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - mountPath: "/var/run/docker.sock"
              name: dockersock
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock