---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: romm-library-smb
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-assets
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-redis
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-bios
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 2Gi
