---
apiVersion: v1
kind: Secret
metadata:
  name: romm-smbcreds
  namespace: romm
type: Opaque
stringData:
  username: <OMV_SMB_USERNAME>
  password: <OMV_SMB_PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: romm-secrets
  namespace: romm
type: Opaque
stringData:
  ROMM_AUTH_SECRET_KEY: <64_HEX_CHARS>
  DB_PASSWD: <DB_PASSWORD>
  MARIADB_ROOT_PASSWORD: <DB_ROOT_PASSWORD>
