repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: kube-system
    chart: traefik/traefik
    version: 21.2.1+up21.2.0
    values:
      - service:
          type: NodePort
      - replicaCount: 1
      - dashboard:
          enabled: false
      - rbac:
          enabled: true
      - ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik
      - ports:
          web:
            nodePort: 30080
          websecure:
            nodePort: 30443
