replicaCount: 1
maxUnavailable: 0

image:
  # fixate the version to use
  # https://hub.docker.com/r/pihole/pihole
  tag: "2025.06.0"

serviceDhcp:
  enabled: false

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole

serviceWeb:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistentVolumeClaim:
  enabled: true

admin:
  existingSecret: "pihole-admin"

extraEnvVars:
  TZ: Europe/Rome
