---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: ["cloudflared", "tunnel", "--config", "/etc/cloudflared/config.yml", "run"]
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared/config.yml    # target file path in pod
              subPath: config.yml                        # exact key name inside ConfigMap
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared/b7f8cb31-94fe-4760-b7ee-b04b097349f3.json
              subPath: b7f8cb31-94fe-4760-b7ee-b04b097349f3.json
              readOnly: true
      volumes:
        - name: cloudflared-config
          configMap:
            name: cloudflared-config
        - name: credentials
          secret:
            secretName: cloudflared-credentials
---
