---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-sensebuilding-sandbox
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-sandbox-sensebuilding
  template:
    metadata:
      labels:
        app: cloudflared-sandbox-sensebuilding
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: ["cloudflared", "tunnel", "--config", "/etc/cloudflared/config.yml", "run"]
          volumeMounts:
            - name: cloudflared-sensebuilding-sandbox-config
              mountPath: /etc/cloudflared/config.yml    # target file path in pod
              subPath: config.yml                        # exact key name inside ConfigMap
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared/1286c0cb-c987-44ee-9f36-47b10f4b96d5.json
              subPath: 1286c0cb-c987-44ee-9f36-47b10f4b96d5.json
              readOnly: true
      volumes:
        - name: cloudflared-sensebuilding-sandbox-config
          configMap:
            name: cloudflared-sensebuilding-sandbox-config
        - name: credentials
          secret:
            secretName: cloudflared-mythic-creds
---
