replicaCount: 1
maxUnavailable: 0

image:
  # fixate the version to use
  # https://hub.docker.com/r/pihole/pihole
  tag: "2025.06.0"

serviceDhcp:
  enabled: false

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole

serviceWeb:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  externalTrafficPolicy: Local
  ports:
    http: 8080
    https: 8443

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistentVolumeClaim:
  enabled: true

adlists:
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/fake.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/popupads.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/dyndns.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-adblock.txt
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
  - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
  - https://big.oisd.nl/
  - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science

whitelist:
  - 0.client-channel.google.com
  - 2.android.pool.ntp.org
  - akamaihd.net
  - akamaitechnologies.com
  - akamaized.net
  - alluremedia.com.au
  - amazonaws.com
  - android.clients.google.com
  - api.ipify.org
  - api.rlje.net
  - app-api.ted.com
  - app.plex.tv
  - appleid.apple.com
  - appsbackup-pa.clients6.google.com
  - appsbackup-pa.googleapis.com
  - aspnetcdn.com
  - attestation.xboxlive.com
  - brightcove.net
  - bufferapp.com
  - c.s-microsoft.com
  - cdn.cloudflare.net
  - cdn.embedly.com
  - cdn.optimizely.com
  - cdn.vidible.tv
  - cdn2.optimizely.com
  - cdn3.optimizely.com
  - cdnjs.cloudflare.com
  - cert.mgt.xboxlive.com
  - clientconfig.passport.net
  - clients1.google.com
  - clients2.google.com
  - clients3.google.com
  - clients4.google.com
  - clients5.google.com
  - clients6.google.com
  - cpms.spop10.ams.plex.bz
  - cpms35.spop10.ams.plex.bz
  - cse.google.com
  - ctldl.windowsupdate.com
  - d2c8v52ll5s99u.cloudfront.net
  - d2gatte9o95jao.cloudfront.net
  - dashboard.plex.tv
  - dataplicity.com
  - def-vef.xboxlive.com
  - delivery.vidible.tv
  - dev.virtualearth.net
  - device.auth.xboxlive.com
  - display.ugc.bazaarvoice.com
  - displaycatalog.mp.microsoft.com
  - dl.delivery.mp.microsoft.com
  - dns.msftncsi.com
  - dynupdate.no-ip.com
  - ec-ns.sascdn.com
  - ecn.dev.virtualearth.net
  - edge.api.brightcove.com
  - eds.xboxlive.com
  - fonts.gstatic.com
  - g.live.com
  - geo-prod.do.dsp.mp.microsoft.com
  - geo3.ggpht.com
  - giphy.com
  - github.com
  - github.io
  - googleapis.com
  - gravatar.com
  - gstatic.com
  - help.ui.xboxlive.com
  - hls.ted.com
  - i.s-microsoft.com
  - i.ytimg.com
  - i1.ytimg.com
  - imagesak.secureserver.net
  - img.vidible.tv
  - imgix.net
  - imgs.xkcd.com
  - instantmessaging-pa.googleapis.com
  - intercom.io
  - j.mp
  - jquery.com
  - jsdelivr.net
  - keystone.mwbsys.com
  - lastfm-img2.akamaized.net
  - licensing.xboxlive.com
  - live.com
  - login.aliexpress.com
  - login.live.com
  - login.microsoftonline.com
  - manifest.googlevideo.com
  - meta-db-worker02.pop.ric.plex.bz
  - meta.plex.bz
  - meta.plex.tv
  - microsoftonline.com
  - msftncsi.com
  - my.plexapp.com
  - nexusrules.officeapps.live.com
  - no-ip.com
  - notify.xboxlive.com
  - ocsp.apple.com
  - om.cbsi.com
  - outlook.live.com
  - outlook.office365.com
  - placeholdit.imgix.net
  - players.brightcove.net
  - raw.githubusercontent.com
  - redirector.googlevideo.com
  - res.cloudinary.com
  - s.gateway.messenger.live.com
  - s.marketwatch.com
  - s.shopify.com
  - s.youtube.com
  - s.ytimg.com
  - s1.wp.com
  - s2.youtube.com
  - s3.amazonaws.com
  - sa.symcb.com
  - secure.avangate.com
  - secure.brightcove.com
  - secure.surveymonkey.com
  - sharepoint.com
  - spclient.wg.spotify.com
  - ssl.p.jwpcdn.com
  - t0.ssl.ak.dynamic.tiles.virtualearth.net
  - t0.ssl.ak.tiles.virtualearth.net
  - tinyurl.com
  - title.auth.xboxlive.com
  - title.mgt.xboxlive.com
  - traffic.libsyn.com
  - tvthemes.plexapp.com
  - twimg.com
  - twitter.com
  - ui.skype.com
  - v.shopify.com
  - video-stats.l.google.com
  - videos.vidible.tv
  - widget-cdn.rpxnow.com
  - wikipedia.org
  - win10.ipv6.microsoft.com
  - wordpress.com
  - wp.com
  - ws.audioscrobbler.com
  - www.dataplicity.com
  - www.googleapis.com
  - www.no-ip.com
  - xbox.ipv6.microsoft.com
  - xboxexperiencesprod.experimentation.xboxlive.com
  - xflight.xboxlive.com
  - xkms.xboxlive.com
  - xsts.auth.xboxlive.com
  - youtu.be
  - youtube-nocookie.com
  - yt3.ggpht.com

admin:
  existingSecret: "pihole-admin"

extraEnvVars:
  TZ: Europe/Rome
  PIHOLE_SETUP_ADLISTS: "true"
  SKIPGRAVITYONBOOT: "false"
